name: E2E Tests

on:
  schedule:
    - cron: '0 2 * * 4'  # Runs every month at 2 AM on Thursday

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
   inputs:
     testsPath:
       description: 'Path to Tests to be Executed'
       default: 'test.cases.Register_User'

jobs:
  E2E_Chrome_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        continue-on-error: true
        run: mvn test -DbrowserName="chrome" -DheadlessExecution="true" -Dtest="${{ github.event.inputs.testsPath }}"

      - name: Generate Allure Report Single File
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Chrome_Linux_Allure
          path: target/site/allure-maven-plugin/index.html

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            target/surefire-reports/TEST-*.xml


  E2E_Edge_Windows_Test:
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        continue-on-error: true
        run: mvn test -DbrowserName="edge" -DheadlessExecution="false" -Dtest="${{ github.event.inputs.testsPath }}"

      - name: Generate Allure Report Single File
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Edge_Windows_Allure
          path: target/site/allure-maven-plugin/index.html


      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: |
            target/surefire-reports/TEST-*.xml
